yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path(
        '',
        views.index,
        name='index',
    ),
    path(
        'group/<slug:slug>/',
        views.groups_posts,
        name='group_list',
    ),
    path(
        'profile/<str:username>/',
        views.profile,
        name='profile',
    ),
    path(
        'posts/<int:post_id>/',
        views.post_detail,
        name='post_detail',
    ),
    path(
        'create/',
        views.post_create,
        name='post_create',
    ),
    path(
        'posts/<post_id>/edit/',
        views.edit,
        name='edit',
    ),
]

yatube/users/urls.py
from django.contrib.auth.views import (
    LogoutView,
    LoginView,
    PasswordResetView,
    PasswordChangeView,
)
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views


app_name = 'users'

urlpatterns = [
    path(
        'signup/',
        views.SignUp.as_view(),
        name='signup',
    ),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout',
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login',
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password/password_change_form.html',
        ),
        name='password_change',
    ),
    path(
        'password_change/done/',
        PasswordChangeView.as_view(
            template_name='users/password/password_change_done.html',
        ),
        name='password_change_done',
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password/password_reset_form.html'
        ),
        name='password_reset_form',
    ),
    path(
        'password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='users/password/password_reset_done.html'
        ),
        name='password_reset_done',
    ),
    path(
        'reset/<uidb64>/token/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='users/passsword/password_reset_confirm.html'
        ),
        name='password_reset_confirm',
    ),
    path(
        'reset/done/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='users/password/password_reset_complete.html'
        ),
        name='password_reset_complete',
    ),
]

yatube/yatube/urls.py
from django.contrib import admin

from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

from .constants import STRING_LENGHT_LIMIT

User = get_user_model()


class Post(models.Model):
    '''Объявляем класс Post, наследник класса Model из пакета models
    Описываем поля модели и их типы'''

    text = models.TextField(
        verbose_name='Текст публикации',
    )
    pub_date = models.DateTimeField(
        verbose_name='Дата публикации',
        auto_now_add=True,
    )
    author = models.ForeignKey(
        User,
        verbose_name='Автор публикации',
        on_delete=models.CASCADE,
        related_name='posts',
    )
    group = models.ForeignKey(
        'Group',
        verbose_name='Сообщество',
        blank=True,
        on_delete=models.SET_NULL,
        null=True,
        related_name='posts',
    )

    class Meta:

        ordering = ('-pub_date',)

    def __str__(self) -> str:
        return self.text[:STRING_LENGHT_LIMIT]


class Group(models.Model):
    '''Объявляем класс Group, наследник класса Model из пакета models
    Описываем поля модели и их типы'''

    title = models.CharField(
        verbose_name='Сообщество',
        max_length=200,
    )
    slug = models.SlugField(
        verbose_name='URL - адрес',
        unique=True,
    )
    description = models.TextField(
        verbose_name='Описание',
    )

    def __str__(self) -> str:
        return self.title

yatube/posts/forms.py
from django import forms

from posts.models import Post


class PostForm(forms.ModelForm):
    '''Класс для формы создания поста'''

    class Meta:

        model = Post
        fields = ('text', 'group')
        labels = {'text': 'Текст поста', 'group': 'Группа поста'}
        help_texts = {
            'text': 'Текст создаваемого поста',
            'group': 'Выбор группы для поста',
        }

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class CreationForm(UserCreationForm):
    '''Класс для формы регистрации'''

    class Meta(UserCreationForm.Meta):
        '''Класс для настривания формы и переопределения параметров'''

        model = User
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
        )

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    '''Класс для обработки страницы Об авторе'''

    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    '''Класс для обработки страницы Технологии'''

    template_name = 'about/tech.html'

yatube/posts/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required

from .models import Post, Group, User
from .utils import pagination
from posts.forms import PostForm


def index(request):
    '''view-функция для главной страницы'''
    template = 'posts/index.html'
    post_list = Post.objects.select_related('author', 'group')
    page_obj = pagination(post_list, request)
    context = {
        'page_obj': page_obj,
    }

    return render(request, template, context)


def groups_posts(request, slug):
    '''view-функция для страницы на которой будут посты'''
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_obj = pagination(posts, request)
    context = {
        'group': group,
        'page_obj': page_obj,
    }

    return render(request, template, context)


def profile(request, username):
    '''Страница профайла пользователя:
    на ней будет отображаться информация об авторе и его посты.'''
    temmplate = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    posts_list = author.posts.all()
    page_obj = pagination(posts_list, request)
    context = {
        'author': author,
        'page_obj': page_obj,
    }

    return render(request, temmplate, context)


def post_detail(request, post_id):
    '''Страница для просмотра отдельного поста.'''
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, pk=post_id)
    context = {
        'post': post,
    }

    return render(request, template, context)


@login_required
def post_create(request):
    '''Страница для публикации постов'''
    template = 'posts/post_create.html'
    form = PostForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        form.save()

        return redirect('posts:profile', username=post.author)

    return render(request, template, {'form': form, 'username': request.user})


@login_required
def edit(request, post_id):
    """Вью-функция изменения публикации"""
    template = 'posts:post_detail'
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect(template, post_id=post_id)

    form = PostForm(request.POST or None, instance=post)
    if request.method == 'POST' and form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        form.save()

        return redirect(template, post_id=post_id)

    form = PostForm(instance=post)

    return render(
        request,
        'posts/post_create.html',
        {'is_edit': True, 'form': form, 'post': post},
    )

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import CreationForm


class SignUp(CreateView):
    '''Клас для регистрации пользователя'''

    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends "base.html" %}

{% load static %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<div class="container py-5">
  <h1>Привет, я автор!</h1>
  <p>
    Меня зовут Александр.
  </p>
  <p>
    Не полных 42 года. Скоро пенсия. <span>&#x1F606</span>
  </p>
  <p>
    Работаю в отделе роботизации (автоматизации).
    Для реализации проектов используем UiPath (очень редко script`оложество). 
  </p>
  <p>
    В основном автоматизируем алгоритмы бухгалтерии и HR:
    SAP, Excel, отправка отчёта на почту заказчика, реже задействуется браузер.
    То что человек делает часами, робот выполняет за минуты.
    Если не ломается. Все счастливы.
  </p>
  <p>
    Попал в IT через тестрирование.
    Обучился, и в бой.
    Год протестировал, предложили автоматизацию.
    Я, естественно, согласился - новый опыт и рост.
    Вывод: уится и меняться очень полезно.
    А главное - не боятся перемен, иногда они положительные.
  </p>
  <p>
    Домашнее жывотное имеется, но только отвлекает.
    Закрытые двери для кота - это Троя для греков.
    Для работы мне необхадима концентрация, помогает электронная музыка в ушах.
  </p>
  <p>
    Решил пройти курсы по Python,
    потому как самостоятельное обучение
    не очень структурировано и послдеовательно.
    Тем более, за счёт компании.
  </p>
  <p>
    Теперь у меня есть акк на GitHub,
    и я умею делать на него ссылку
    (а в качестве лейбла питомец. кликабельно)
  </p>
      <a href="https://github.com/AlGenSo" target="_blank">
        <img src="{% static 'img/GitCat.jpg' %}"
        width="115" height="150">
      </a>
      <p></p>
  <p>
    К сожалению, не располгаю временем, что бы навести тут красоту.
      <span>&#x1F614</span>
  </p>
<div>
{% endblock %}

yatube/templates/about/tech.html
{% extends "base.html" %}

{% load static %}
{% block title %}Технологии{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row">
    <h1>Вот что я, якобы, умею</h1>
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Python
        </li>
        <li class="list-group-item">
          Django
        </li>
        <li class="list-group-item">
          VSC
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <p>
        <h3>Тут я вкратце расскажу о том, как я создавал данный сайт.</h3>
      </p>
      <p>
        В первую очередь создал git-репозиторий.
      </p>
      <p>
        Затем установил и настроил Visual Studio Code
        - это редактор, но при этом обладающий функциями IDE.
      </p>
      <p>
        Настроил окружение venv, puthon.
      </p>
      <p>
        Использовал HTML и CSS, Bootstrap.
      </p>
      <p>
        И поехало: Приложения, классы, модули, шаблоны.
      </p>
      <p>
        В голове сначала каша, и глаза размером с блюдце.
      </p>
      <p>
        Но, потом, после неоднократного прочтения задания,
        вроде начинаешь понимать с чего начать,
        а это уже пол дела.
      </p>
      <p></p>
      <p>
        Очень интересно звниматься именно вёрсткой. Но нужно больше практики.
      </p>
      <p>
        Сложно даётся понимание взаимодействия шаблонов.
        Что, как и куда передаётся.
        <br>Вроде всё ясно, пока читаешь теорию,
        но как дело доходит до практики...
      </p>
      <p>
         При неизбежных затыках с задачами,
         выручают, в основном, сокурсники в Slack.
      </p>
      <p>
        Ну вот пишу сейчас текст, а сам смотрю на файлы в боковой панели,
        и вроде всё понятно, что и как работает :)
      </p>
      <p>
        Хотелось бы больше времени уделять учёбе, читать больше статей.
      </p>
      <p>
        Думаю практика со временем заполнит не все, но многие пробелы.
      </p>
    </article>
  </div>
</div>
{% endblock %}

yatube/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{%  static 'img/fav/fav.ico'  %}" type="image">
    <link rel="apple-touch-icon"
      sizes="180x180" href="{%  static 'img/fav/apple-touch-icon.png'  %}">
    <link rel="icon" type="image/png"
      sizes="32x32" href="{%  static 'img/fav/favicon-32x32.png'  %}">
    <link rel="icon" type="image/png"
      sizes="16x16" href="{%  static 'img/fav/favicon-16x16.png'  %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{%  static 'css/bootstrap.min.css'  %}">
    <title>
      {%  block title  %}
        Ушли на обед
      {%  endblock  %}
    </title>
  </head>
  <body>
    <header>
      {%  include 'includes/header.html'  %}
    </header>
    <main>
      {%  block content  %}
          Скоро тут всё появится!
      {%  endblock   %}
    </main>
    <footer class="border-top text-center py-3">
      {%  include 'includes/footer.html'  %}
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
<p
  style="text-align: center;">&copy;
  {{ year }} Copyright <span style="color:red">Ya</span>tube
</p>

yatube/templates/includes/form_errors.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}

yatube/templates/includes/form_group.html
{% load user_filters %}
<div class="form-group row my-3 p-3"
  aria-required="{% if field.field.required %}true{% else %}false{% endif %}">
    <label for="{{ field.id_for_label }}">
      {{ field.label }}
      {% if field.field.required %}
        <span class="required text-danger">*</span>
      {% endif %}
    </label>
    {{ field|addclass:'form-control' }}
    {% if field.help_text %}
      <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
        {{ field.help_text|safe }}
      </small>
    {% endif %}
</div>

yatube/templates/includes/header.html
{% load static %}

{% with request.resolver_match.view_name as view_name  %}
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{%  static 'img/logo.png'  %}"
          width="30" height="30"
          class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      <ul class="nav nav-pills">
        <li class="nav-item">
          <a class="
            nav-link
            {% if view_name == 'about:author' %}
              active
            {% endif %}
          "
          href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="
            nav-link
            {% if view_name == 'about:tech' %}
              active
            {% endif %}
          "
          href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link
              {% if view_name  == 'posts:post_create' %}
                active
              {% endif %}"
            href="{% url 'posts:post_create' %}">
            Новая запись
            </a>
          </li>
          <li class="nav-item">
            <a
              class="nav-link link-light
                {% if view_name  == 'users:password_change' %}
                  active
                {% endif %}"
              href="{% url 'users:password_change' %}">
              Изменить пароль
            </a>
          </li>
          <li class="nav-item">
            <a class="
              nav-link link-light
              {% if view_name == 'users:logout' %}
                active
              {% endif %}
            "
            href="{% url 'users:logout' %}">Выйти</a>
          </li>
          <li>
            Пользователь: {{ user.username }}
          </li>
          {% else %}
          <li class="nav-item">
            <a class="
              nav-link link-light
              {% if view_name == 'users:login' %}
                active
              {% endif %}
            "
            href="{% url 'users:login' %}">Войти</a>
          </li>
          <li class="nav-item">
            <a class="
              nav-link link-light
              {% if view_name == 'users:signup' %}
                active
              {% endif %}
            "
            href="{% url 'users:signup' %}">Регистрация</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>
{% endwith %}

yatube/templates/posts/group_list.html
{%  extends 'base.html'  %}

{% load static %}
{%  block title  %}
  {% autoescape on %}
    Записи сообщества {{ group.title }}
  {% endautoescape %}
{%  endblock  %}
{%  block content  %}
  <div class="container py-5"
    href="{% url 'posts:group_list' group.slug %}">
    <div style="float:left; padding-right:30px;">
      <img src="{% static 'img/LNT.png' %}"
      width="75" height="80" alt="">
    </div>
    <h1>
      {% autoescape on %}
        {{ group.title }}
      {% endautoescape %}
    </h1>
      <p>{{ group.description }}</p>
      {%  for post in page_obj  %}
      {% include 'posts/includes/detailed_information.html' %}
      {%  if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
  </div>
{%  endblock  %}

yatube/templates/posts/includes/detailed_information.html
<article>
  <ul>
  <li>
    Автор: {{ author.get_full_name }}
    <a href="{% url 'posts:profile' post.author.username %}">
      все посты пользователя
    </a>
  </li>
  <li>
    Дата публикации: {{ post.pub_date|date:"d E Y" }}
  </li>
  </ul>
  <p>
    {{ post.text|linebreaks }}
  </p>
  <a href="{% url 'posts:post_detail' post.id %}">
    подробная информация
  </a>
  {% if not group and post.group %}
    Группа: {{ post.group.title }}
      <a href="{% url 'posts:group_list' post.group.slug %}">
        все записи группы
      </a>
  {% endif %}
  </article>

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/index.html
{%  extends 'base.html'  %}

{%  block title  %}
  {% autoescape on %}
    Последние обновления на сайте
  {% endautoescape %}
{%  endblock  %}
{%  block content  %}
<div class="container py-5">
  <h1>
    {% autoescape on %}
      Последние обновления на сайте
    {% endautoescape %}
  </h1>
  {%  for post in page_obj  %}
  {% include 'posts/includes/detailed_information.html' %}
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
</div>
{%  endblock  %}

yatube/templates/posts/post_create.html
{%  extends 'base.html'  %}

{% load static %}
{%  block title  %}
  {% autoescape on %}
    {% if not is_edit %}
      Добавиь запись
    {% else %}
      Радактировать запись
    {% endif %}
  {% endautoescape %}
{%  endblock  %}
{%  block content  %}
<div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if not is_edit %}
              Новый пост
            {% else %}
              Редактировать пост
            {% endif %}
          </div>
          <div class="card-body">
            
            {%  include 'includes/form_errors.html'  %}

            <form method="post"
              action="
                {% if is_edit %}
                  {% url 'posts:edit' post.id %}
                {% else %}
                  {% url 'posts:post_create' %}
                {% endif %}"
            >
            {% csrf_token %}

              {% for field in form %}
                {%  include 'includes/form_group.html'  %}
              {% endfor %}

              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{%  endblock  %}

yatube/templates/posts/post_detail.html
{%  extends 'base.html'  %}

{% load static %}
{%  block title  %}
  {% autoescape on %}
    Пост {{ post|truncatechars:30 }}
  {% endautoescape %}
{%  endblock  %}
{%  block content  %}
<div class="container py-5">
<div class="row">
<aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
    <li class="
      list-group-item d-flex
      justify-content-between
      align-items-center">
        Дата публикации: <br>{{ post.pub_date|date:"d E Y" }}
    </li>
    {% if post.group %}
        <li class="list-group-item">
        Группа: {{ post.group.title }}<br>
         <a href="{% url 'posts:group_list' post.group.slug %}">
           все записи группы
         </a>
        </li>
    {% endif %}
        <li class="
          list-group-item d-flex
          justify-content-between
          align-items-center">
          Автор:
            <span >
              {{ post.author.get_full_name }}
            </span>
        </li>
        <li class="
          list-group-item d-flex
          justify-content-between
          align-items-center"
        >
        Всего постов автора:
          <span >
            {{ author.posts.all.count }}
          </span>
    </li>
    <li class="list-group-item">
        <a href="{% url 'posts:profile' post.author.username %}">
        все посты пользователя
        </a>
    </li>
    </ul>
</aside>
<article class="col-12 col-md-9">
    <p>
      {{ post.text|linebreaks }}
      <div class="d-flex justify-content-end">
        {% if user == post.author %}
          <a href="{% url 'posts:edit' post.id %}"
            class="btn btn-primary">
            Редактировать
          </a>
       {% endif %}
      </div>
    </p>
</article>
</div>
</div>
{%  endblock  %}

yatube/templates/posts/profile.html
{%  extends 'base.html'  %}

{% load static %}
{%  block title  %}
  {% autoescape on %}
    Профайл пользователя
    {% if post.author.get_full_name %}
      {{ .post.author.get_full_name }}
    {% else %}
      {{ author.username }}
    {% endif %}
  {% endautoescape %}
{%  endblock  %}
{%  block content  %}
<div class="container py-5">
  <h1>
    Все посты пользователя: {{ post.author.get_full_name }}
  </h1>
  <h3>Всего постов: {{ author.posts.all.count }}</h3>
  {% for post in page_obj %}
  {% include 'posts/includes/detailed_information.html' %}
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
</div>
{%  endblock  %}
 

yatube/templates/users/logged_out.html
{% extends 'base.html' %}

{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}

{% load static %}
{% block title %}Войти на сайт{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">

          {%  include 'includes/form_errors.html'  %}

          <form method="post" action="{% url 'users:login' %}">
          {% csrf_token %}

          {% for field in form %}
            {%  include 'includes/form_group.html'  %}
          {% endfor %}

          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <a
              href="{% url 'users:password_reset_form' %}"
              class="btn btn-link"
            >
              Забыли пароль?
            </a>
          </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/password/password_change_done.html
{% extends 'base.html' %}

{% block title %}Пароль изменён{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Пароль изменён
        </div>
          <div class="card-body">
            <p>Пароль изменён успешно</p>
          </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/password/password_change_form.html
{% extends 'base.html' %}

{% block title %}Изменить пароль{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Изменить пароль
        </div>
          <div class="card-body">
            <form method="post"
            {% if action_url %}
                action="{% url action_url %}"
            {% endif %}
            {% csrf_token %}
            <div class="form-group row my-3 p-3">
            <label for="id_old_password">
                Старый пароль
                <span class="required text-danger">*</span>
            </label>
            <input
                type="password"
                name="old_password"
                autofocus class="form-control"
                required id="id_old_password"
            >
            </div>
            <div class="form-group row my-3 p-3">
            <label for="id_new_password1">
                Новый пароль
                <span class="required text-danger">*</span>
            </label>
            <input
                type="password"
                name="new_password1"
                class="form-control"
                required id="id_new_password1"
            >
                <small
                id="id_new_password1-help"
                class="form-text text-muted"
                >
                <ul>
                    <li>
                    Ваш пароль не должен совпадать с вашим именем
                    или другой персональной информацией
                    или быть слишком похожим на неё.
                    </li>
                    <li>
                    Ваш пароль должен содержать как минимум 8 символов.
                    </li>
                    <li>
                    Ваш пароль не может быть одним
                    из широко распространённых паролей.
                    </li>
                    <li>
                    Ваш пароль не может состоять только из цифр.
                    </li>
                </ul>
                </small>
            </div>
            <div class="form-group row my-3 p-3">
            <label for="id_new_password2">
                Подтверждение нового пароля
                <span class="required text-danger">*</span>
            </label>
            <input
                type="password"
                name="new_password2"
                class="form-control"
                required id="id_new_password2"
            >
            </div>
            <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
                Изменить пароль
            </button>
            </div>
            </form>
          </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/password/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
<main>
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Пароль был изменен!
          </div>
          <div class="card-body">
            <p>Ваш пароль был сохранен. Используйте его для входа</p>
            <a href="{% url 'users:login' %}">Войти</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}

{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
            {% load user_filters %}

              {%  include 'includes/form_errors.html'  %}

              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}

              {% for field in form %}
                {%  include 'includes/form_group.html'  %}
              {% endfor %}

              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
  </div>
{% endblock %}